INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10000', '12', 'Scharnweberstrasse', 'neu', '12459');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10001', '42', 'Weserstrasse', 'neu', '12045');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10002', '33', 'Sonnenallee', 'zugeordnet', '12047');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10003', '5', 'Gleimstrasse', 'abgeholt', '13355');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10004', '66', 'Reinickendorferstrasse', 'neu', '13347');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10005', '77', 'Hobrechtstrasse', 'neu', '12043');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10006', '196', 'Frankfurter Allee', 'zugeordnet', '10365');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10007', '99', 'Prenzlauer Allee', 'abgeholt', '10405');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10008', '1', 'Hufelandstrasse', 'neu', '10407');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10009', '2', 'Gutsmuthsstrasse', 'neu', '12163');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10010', '3', 'Willy-Brandt-Strasse', 'zugeordnet', '10557');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10011', '4', 'Schlesische Strasse', 'abgeholt', '10997');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10012', '5', 'Schoenhauser Allee', 'neu', '10119');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10013', '6', 'Am Flutgraben', 'neu', '10119');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10014', '7', 'Paul-Lincke-Ufer', 'zugeordnet', '10999');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10015', '8', 'Pankstrasse', 'abgeholt', '13127');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10016', '9', 'Strasse des 17. Juni', 'neu', '10557');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10017', '10', 'Unter den Linden', 'neu', '10117');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10018', '11', 'Kurfürstendamm', 'zugeordnet', '10719');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10019', '12', 'Friedrichstrasse', 'abgeholt', '10117');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10020', '13', 'Alexanderplatz', 'neu', '10178');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10021', '22', 'Charlottenstrasse', 'neu', '12683');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10022', '12', 'Alexanderstrasse', 'zugeordnet', '10179');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10023', '34', 'Friedrichstrasse', 'neu', '10969');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10024', '55', 'Unter den Linden', 'ausgeliefert', '10117');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10025', '67', 'Kurfürstendamm', 'neu', '10707');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10026', '89', 'Potsdamer Platz', 'zugeordnet', '10117');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10027', '32', 'Schloßstrasse', 'abgeholt', '14059');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10028', '24', 'Budapester Strasse', 'ausgeliefert', '10787');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10029', '36', ' Schönhauser Allee', 'neu', '10435');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10030', '3', 'Archibaldweg', 'zugeordnet', '10317');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10031', '57', 'Badstraße', 'abgeholt', '13357');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10032', '64', 'Schönhauser Allee', 'ausgeliefert', '10437');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10033', '76', 'Gleimstraße', 'neu', '13355');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10034', '98', 'Rosenthaler Straße', 'zugeordnet', '10119');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10035', '47', 'Stargarder Straße', 'abgeholt', '10437');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10036', '12', 'Invalidenstraße', 'ausgeliefert', '10115');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10037', '24', 'Berliner Straße', 'neu', '13507');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10038', '36', 'Friedrichstraße', 'zugeordnet', '10969');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10039', '55', 'Eberswalder Straße', 'abgeholt', '10969');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10040', '67', 'Kastanienallee', 'ausgeliefert', '13158');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10041', '10', 'Leipziger Straße', 'neu', '10117');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10042', '15', 'Unter den Linden', 'zugeordnet', '10117');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10043', '5', 'Kurfürstendamm', 'abgeholt', '10117');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10044', '12', 'Alexanderplatz', 'ausgeliefert', '10178');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10045', '7', 'Prenzlauer Allee', 'neu', '10405');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10046', '11', 'Landsberger Allee', 'zugeordnet', '12681');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10047', '8', 'Hermannstraße', 'abgeholt', '14109');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10048', '9', 'Greifswalder Straße', 'ausgeliefert', '10405');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10049', '4', 'Flughafenstraße', 'neu', '12053');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10050', '2', 'Wilhelmstraße', 'zugeordnet', '13467');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10051', '6', 'Köpenicker Straße', 'abgeholt', '12524');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10052', '13', 'Eberswalder Straße', 'ausgeliefert', '10437');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10053', '14', 'Frankfurter Allee', 'neu', '10247');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10054', '16', 'Nürnberger Straße', 'zugeordnet', '10789');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10055', '18', 'Leipziger Straße', 'abgeholt', '10117');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10056', '19', 'Danziger Straße', 'ausgeliefert', '10435');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10057', '20', 'Hohenzollerndamm', 'neu', '10717');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10058', '22', 'Schönhauser Allee', 'zugeordnet', '10435');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10059', '23', 'Württembergstraße', 'abgeholt', '10437');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10060', '24', 'Badstraße', 'ausgeliefert', '13357');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10061', '3', 'Schönhauser Allee', 'zugeordnet', '10119');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10062', '2', 'Gleimstraße', 'zugeordnet', '13355');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10063', '4', 'Rosenthaler Straße', 'zugeordnet', '13127');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10064', '7', 'Stargarder Straße', 'zugeordnet', '10437');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10065', '12', 'Invalidenstraße', 'neu', '10115');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10066', '15', 'Berliner Straße', 'zugeordnet', '13127');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10067', '9', 'Friedrichstraße', 'zugeordnet', '10969');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10068', '17', 'Eberswalder Straße', 'zugeordnet', '10437');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10069', '19', 'Kastanienallee', 'abgeholt', '13158');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10070', '13', 'Leipziger Straße', 'zugeordnet', '10117');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10071', '8', 'Prenzlauer Allee', 'neu', '10405');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10072', '11', 'Oranienburger Straße', 'zugeordnet', '10178');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10073', '5', 'Nürnberger Straße', 'zugeordnet', '12309');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10074', '6', 'Schliemannstraße', 'zugeordnet', '10437');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10075', '10', 'Greifswalder Straße', 'zugeordnet', '10405');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10076', '18', 'Bölschestraße', 'neu', '12587');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10077', '14', 'Wörther Straße', 'zugeordnet', '10405');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10078', '16', 'Alexanderstraße', 'abgeholt', '10178');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10079', '1', 'Schönleinstraße', 'neu', '10967');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10080', '20', 'Sorbische Straße', 'zugeordnet', '13349');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10081', '42', 'Alt-Moabit', 'neu', '10555');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10082', '15', 'Charlottenstraße', 'zugeordnet', '13156');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10083', '57', 'Unter den Linden', 'abgeholt', '10117');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10084', '12', 'Kurfürstendamm', 'ausgeliefert', '10719');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10085', '34', 'Alexanderplatz', 'neu', '10178');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10086', '9', 'Prenzlauer Allee', 'zugeordnet', '10405');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10087', '27', 'Friedrichstraße', 'abgeholt', '13125');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10088', '47', 'Schönhauser Allee', 'ausgeliefert', '10437');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10089', '18', 'Schloßstraße', 'neu', '14059');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10090', '35', 'Kastanienallee', 'zugeordnet', '13158');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10091', '62', 'Stralauer Allee', 'abgeholt', '10245');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10092', '19', 'Mainzer Straße', 'ausgeliefert', '12053');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10093', '53', 'Hauptstraße', 'neu', '10317');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10094', '29', 'Danziger Straße', 'zugeordnet', '10435');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10095', '48', 'Gneisenaustraße', 'abgeholt', '10961');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10096', '37', 'Frankfurter Allee', 'ausgeliefert', '10247');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10097', '26', 'Rosa-Luxemburg-Platz', 'neu', '10178');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10098', '17', 'Rudi-Dutschke-Straße', 'zugeordnet', '10969');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10099', '44', 'Oranienburger Straße', 'abgeholt', '13437');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10100', '12', 'Chausseestrasse', 'neu', '10115');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10101', '5', 'Unter den Linden', 'zugeordnet', '10117');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10102', '7', 'Prenzlauer Allee', 'abgeholt', '10405');
INSERT INTO Lieferung (LieferId, LieferHausnummer, LieferStrasse, status, LieferPLZ) VALUES ('10103', '8', 'Schlossstrasse', 'ausgeliefert', '14059');