INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1000', 'gemuese', '5', '10000', 'Kurfürstendamm', '456', 'SusiSorglos');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1001', 'fleisch', '3', '10001', 'Hauptstraße', '78', 'KlausKäse');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1002', 'fisch', '8', '10002', 'Schloßstraße', '90', 'JuliaJogurt');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1003', 'milchprodukte', '1', '10003', 'Sonnenallee', '12', 'HansHummus');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1004', 'teigwaren', '10', '10004', 'Mauerstraße', '34', 'PetraPesto');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1005', 'getraenke', '2', '10005', 'Köpenicker Straße', '56', 'FrankFrikadelle');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1006', 'speisereste', '5', '10006', 'Karl-Marx-Allee', '78', 'GabiGurke');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1007', 'sonstiges', '7', '10007', 'Eberswalder Straße', '90', 'KathrinKohlrabi');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1008', 'tiefkuehlprodukte', '4', '10008', 'Greifswalder Straße', '12', 'LarsLinsen');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1009', 'gemuese', '1', '10009', 'Böckhstraße', '34', 'MonikaMöhren');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1010', 'fleisch', '2', '10010', 'Fehrbelliner Straße', '56', 'NicoNudeln');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1011', 'fisch', '3', '10011', 'Herrfurthstraße', '78', 'OliverÖl');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1012', 'milchprodukte', '4', '10012', 'Mainzer Straße', '90', 'PaulPaprika');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1013', 'teigwaren', '5', '10013', 'Oderstraße', '12', 'QuirinQuiche');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1014', 'getraenke', '6', '10014', 'Müllerstraße', '5', 'Einkaufsgenie');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1015', 'speisereste', '7', '10015', 'Kurfürstendamm', '23', 'FoodsharingFan');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1016', 'sonstiges', '8', '10016', 'Hauptstraße', '42', 'Lebensmittelretter');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1017', 'tiefkuehlprodukte', '9', '10017', 'Schönhauser Allee', '32', 'BerlinerGourmet');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1018', 'gemuese', '10', '10018', 'Budapester Straße', '18', 'FoodwasteGegner');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1019', 'fleisch', '1', '10019', 'Prenzlauer Allee', '99', 'NachhaltigerEinkauf');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1020', 'fisch', '3', '10020', 'Köpenicker Straße', '12', 'LebensmittelSparfuchs');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1021', 'milchprodukte', '5', '10021', 'Friedrichstraße', '57', 'FoodsharingBerliner');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1022', 'teigwaren', '2', '10022', 'Invalidenstraße', '112', 'BerlinerGenießer');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1023', 'getraenke', '7', '10023', 'Oranienburger Straße', '45', 'NachhaltigerLebensstil');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1024', 'speisereste', '1', '10024', 'Unter den Linden', '6', 'BerlinerEsser');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1025', 'sonstiges', '6', '10025', 'Leipziger Straße', '78', 'BerlinerFoodsharing');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1026', 'tiefkuehlprodukte', '4', '10026', 'Alexanderstraße', '5', 'BerlinerSparfuchs');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1027', 'gemuese', '8', '10027', 'Weddinger Straße', '12', 'LebensmittelRetter');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1028', 'fleisch', '10', '10028', 'Kurfürstendamm', '78', 'Imbiss am Zoo');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1029', 'fisch', '9', '10029', 'Wilmersdorfer Str.', '112', 'Supermarkt Netto');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1030', 'milchprodukte', '1', '10030', 'Mainzer Str.', '15', 'Restaurant Vöner');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1031', 'teigwaren', '3', '10031', 'Gneisenaustr.', '32', 'Café Kaffeebud');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1032', 'getraenke', '4', '10032', 'Kurfürstendamm', '24', 'Lutter & Wegner');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1033', 'speisereste', '5', '10033', 'Prenzlauer Allee', '4', 'Imbiss am Alexanderplatz');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1034', 'sonstiges', '2', '10034', 'Schönhauser Allee', '36', 'Pizza Express');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1035', 'tiefkuehlprodukte', '7', '10035', 'Friedrichstraße', '99', 'Café am Neuen See');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1036', 'gemuese', '9', '10036', 'Kantstraße', '149', 'Bistro Französisch');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1037', 'fleisch', '8', '10037', 'Unter den Linden', '5', 'Kaffeehaus am Brandenburger Tor');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1038', 'fisch', '1', '10038', 'Willy-Brandt-Straße', '51', 'Imbiss am Potsdamer Platz');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1039', 'milchprodukte', '6', '10039', 'An der Spandauer Brücke', '1', 'Restaurant Spandau');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1040', 'teigwaren', '4', '10040', 'Hauptstraße', '26', 'Bäckerei Schmidt');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1041', 'getraenke', '8', '10041', 'Grunewaldstraße', '58', 'Supermarkt Edeka');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1042', 'speisereste', '9', '10042', 'Gneisenaustr.', '32', 'Café Kaffeebud');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1043', 'sonstiges', '7', '10043', 'Kurfürstendamm', '24', 'Lutter & Wegner');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1044', 'tiefkuehlprodukte', '2', '10044', 'Prenzlauer Allee', '4', 'Imbiss am Alexanderplatz');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1045', 'gemuese', '3', '10045', 'Schönhauser Allee', '36', 'Pizza Express');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1046', 'fleisch', '5', '10046', 'Friedrichstraße', '99', 'Café am Neuen See');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1047', 'fisch', '6', '10047', 'Kantstraße', '149', 'Bistro Französisch');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1048', 'milchprodukte', '10', '10048', 'Unter den Linden', '5', 'Kaffeehaus am Brandenburger Tor');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1049', 'teigwaren', '1', '10049', 'Willy-Brandt-Straße', '51', 'Imbiss am Potsdamer Platz');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1050', 'getraenke', '7', '10050', 'An der Spandauer Brücke', '1', 'Restaurant Spandau');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1051', 'speisereste', '2', '10051', 'Hauptstraße', '26', 'Bäckerei Schmidt');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1052', 'sonstiges', '8', '10052', 'Grunewaldstraße', '58', 'Supermarkt Edeka');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1053', 'tiefkuehlprodukte', '3', '10053', 'Lützowstraße', '12', 'Imbiss am Zoo');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1054', 'gemuese', '9', '10054', 'Schloßstraße', '34', 'Café am Schloss Charlottenburg');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1055', 'fleisch', '4', '10055', 'Fasanenstraße', '78', 'Restaurant Zum Löwen');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1056', 'fisch', '5', '10056', 'Knesebeckstraße', '32', 'Café Kranzler');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1057', 'milchprodukte', '6', '10057', 'Alexanderstr.', '7', 'Café Adler');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1058', 'teigwaren', '7', '10058', 'Kurfürstendamm', '21', 'Imbiss 21');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1059', 'getraenke', '8', '10059', 'Unter den Linden', '5', 'Restaurant Unter den Linden');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1060', 'speisereste', '10', '10060', 'Prenzlauer Allee', '72', 'Bäckerei Prenzlauer Allee');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1061', 'sonstiges', '1', '10061', 'Schönhauser Allee', '64', 'Supermarkt 64');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1062', 'tiefkuehlprodukte', '9', '10062', 'Invalidenstr.', '48', 'Pizzeria Invalidenstr.');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1063', 'gemuese', '2', '10063', 'Hauptstr.', '120', 'Metzgerei Hauptstr.');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1064', 'fleisch', '3', '10064', 'Neue Bahnhofstr.', '9', 'Café Neue Bahnhofstr.');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1065', 'fisch', '4', '10065', 'Frankfurter Allee', '80', 'Imbiss 80');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1066', 'milchprodukte', '5', '10066', 'Schönhauser Allee', '127', 'Restaurant Schönhauser Allee');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1067', 'teigwaren', '6', '10067', 'Prenzlauer Allee', '198', 'Bäckerei Prenzlauer Allee');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1068', 'getraenke', '7', '10068', 'Köpenicker Straße', '56', 'FrankFrikadelle');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1069', 'speisereste', '8', '10069', 'Sonnenallee', '12', 'HansHummus');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1070', 'sonstiges', '9', '10070', 'Prenzlauer Allee', '99', 'NachhaltigerEinkauf');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1071', 'tiefkuehlprodukte', '10', '10071', 'Köpenicker Straße', '12', 'LebensmittelSparfuchs');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1072', 'gemuese', '1', '10072', 'Friedrichstraße', '57', 'FoodsharingBerliner');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1073', 'fleisch', '2', '10073', 'Invalidenstraße', '112', 'BerlinerGenießer');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1074', 'fisch', '3', '10074', 'Oranienburger Straße', '45', 'NachhaltigerLebensstil');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1075', 'milchprodukte', '4', '10075', 'Unter den Linden', '6', 'BerlinerEsser');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1076', 'teigwaren', '5', '10076', 'Leipziger Straße', '78', 'BerlinerFoodsharing');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1077', 'getraenke', '6', '10077', 'Alexanderstraße', '5', 'BerlinerSparfuchs');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1078', 'speisereste', '7', '10078', 'Weddinger Straße', '12', 'LebensmittelRetter');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1079', 'sonstiges', '8', '10079', 'Kurfürstendamm', '78', 'Imbiss am Zoo');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1080', 'tiefkuehlprodukte', '9', '10080', 'Wilmersdorfer Str.', '112', 'Supermarkt Netto');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1081', 'gemuese', '10', '10081', 'Mainzer Str.', '15', 'Restaurant Vöner');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1082', 'fleisch', '1', '10082', 'Gneisenaustr.', '32', 'Café Kaffeebud');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1083', 'fisch', '2', '10083', 'Kurfürstendamm', '24', 'Lutter & Wegner');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1084', 'milchprodukte', '3', '10084', 'Prenzlauer Allee', '4', 'Imbiss am Alexanderplatz');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1085', 'teigwaren', '4', '10085', 'Schönhauser Allee', '36', 'Pizza Express');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1086', 'getraenke', '5', '10086', 'Schloßstraße', '90', 'JuliaJogurt');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1087', 'speisereste', '6', '10087', 'Köpenicker Straße', '56', 'FrankFrikadelle');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1088', 'sonstiges', '7', '10088', 'Müllerstraße', '10', 'Lieferservice Pizzeria');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1089', 'tiefkuehlprodukte', '8', '10089', 'Kurfürstendamm', '52', 'Café Central');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1090', 'gemuese', '9', '10090', 'Schönhauser Allee', '13', 'Supermarkt Edeka');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1091', 'fleisch', '10', '10091', 'Hauptstraße', '23', 'Bäckerei Schmidt');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1092', 'fisch', '1', '10092', 'Friedrichstraße', '123', 'Restaurant Zum Goldenen Lamm');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1093', 'milchprodukte', '2', '10093', 'Unter den Linden', '12', 'Café Einstein');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1094', 'teigwaren', '3', '10094', 'Gneisenaustraße', '56', 'Imbiss Curry 36');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1095', 'getraenke', '4', '10095', 'Mehringdamm', '89', 'Türkisches Restaurant');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1096', 'speisereste', '5', '10096', 'Neue Promenade', '4', 'Sushi-Bar');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1097', 'sonstiges', '6', '10097', 'Kastanienallee', '78', 'Eiscafé');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1098', 'tiefkuehlprodukte', '7', '10098', 'Kantstraße', '12', 'Café am Neuen See');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1099', 'gemuese', '8', '10099', 'Köpenicker Straße', '56', 'FrankFrikadelle');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1100', 'fleisch', '9', '10100', 'Schloßstraße', '90', 'JuliaJogurt');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1101', 'fisch', '10', '10101', 'Frankfurter Allee', '80', 'Imbiss 80');
INSERT INTO Spende (SpendenId, Kategorie, Menge, LieferId, SpenderStrasse, SpenderHausnummer, SpenderName) VALUES ('1102', 'milchprodukte', '1', '10102', 'Frankfurter Allee', '80', 'Imbiss 80');