INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Müllerstraße', '2', 'Café Mitte', '10117');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Kurfürstendamm', '23', 'Restaurant Berlin', '10787');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Alexanderplatz', '5', 'Imbiss am Alex', '10178');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Hauptstraße', '12', 'Pizzeria am See', '12159');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Schloßstraße', '1', 'Bäckerei am Schloss', '12165');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Unter den Linden', '6', 'Eiscafé am Brandenburger Tor', '10117');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Budapester Straße', '45', 'Burger King', '10787');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Lützowstraße', '15', 'McDonalds', '10785');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Charlottenstraße', '30', 'Starbucks', '10117');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Kastanienallee', '56', 'Subway', '10435');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Schönhauser Allee', '78', 'Penny Markt', '10437');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Greifswalder Straße', '4', 'Netto', '10405');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Oranienstraße', '34', 'Aldi', '10999');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Grunerstraße', '22', 'Lidl', '10179');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Eberswalder Straße', '16', 'Edeka', '10437');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Köpenicker Straße', '50', 'Rewe', '10317');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Alexanderstr.', '7', 'Café Einstein', '10178');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Unter den Linden', '1', 'Imbiss am Brandenburger Tor', '10117');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Kurfürstendamm', '23', 'Café Kranzler', '10707');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Friedrichstr.', '45', 'Pizzeria Napoli', '10117');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Schönhauser Allee', '146', 'Bäckerei Schmidt', '10435');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Hauptstr.', '31', 'Supermarkt Edeka', '10715');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Oranienstr.', '67', 'Restaurant Zum Goldenen Lamm', '10999');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Kastanienallee', '56', 'Café Kaffeebud', '10435');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Mainzer Str.', '15', 'Imbiss am Mainzer Bahnhof', '10247');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Gneisenaustr.', '32', 'Restaurant Vöner', '10961');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Prenzlauer Allee', '187', 'Café Prenzlauer Allee', '10405');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Kurfürstendamm', '78', 'Imbiss am Zoo', '10787');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Wilmersdorfer Str.', '112', 'Supermarkt Netto', '10629');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Mainzer Str.', '15', 'Restaurant Vöner', '10247');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Gneisenaustr.', '32', 'Café Kaffeebud', '10961');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Kurfürstendamm', '24', 'Lutter & Wegner', '10707');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Prenzlauer Allee', '4', 'Imbiss am Alexanderplatz', '10405');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Schönhauser Allee', '36', 'Pizza Express', '10435');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Friedrichstraße', '99', 'Café am Neuen See', '10117');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Kantstraße', '149', 'Bistro Französisch', '10623');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Unter den Linden', '5', 'Kaffeehaus am Brandenburger Tor', '10117');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Willy-Brandt-Straße', '51', 'Imbiss am Potsdamer Platz', '10963');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('An der Spandauer Brücke', '1', 'Restaurant Spandau', '13597');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Hauptstraße', '26', 'Bäckerei Schmidt', '12159');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Grunewaldstraße', '58', 'Supermarkt Edeka', '14193');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Lützowstraße', '12', 'Imbiss am Zoo', '10785');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Schloßstraße', '34', 'Café am Schloss Charlottenburg', '14059');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Fasanenstraße', '78', 'Restaurant Zum Löwen', '10719');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Knesebeckstraße', '32', 'Café Kranzler', '10623');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Alexanderstr.', '7', 'Café Adler', '10178');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Kurfürstendamm', '21', 'Imbiss 21', '10719');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Unter den Linden', '5', 'Restaurant Unter den Linden', '10117');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Prenzlauer Allee', '72', 'Bäckerei Prenzlauer Allee', '10405');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Schönhauser Allee', '64', 'Supermarkt 64', '10435');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Invalidenstr.', '48', 'Pizzeria Invalidenstr.', '10115');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Hauptstr.', '120', 'Metzgerei Hauptstr.', '13187');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Neue Bahnhofstr.', '9', 'Café Neue Bahnhofstr.', '10317');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Frankfurter Allee', '80', 'Imbiss 80', '10247');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Schönhauser Allee', '127', 'Restaurant Schönhauser Allee', '10435');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Prenzlauer Allee', '198', 'Bäckerei Prenzlauer Allee', '10405');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Oranienburger Str.', '71', 'Supermarkt Oranienburger Str.', '10117');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Lützner Str.', '42', 'Pizzeria Lützner Str.', '10435');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Wedding Str.', '33', 'Metzgerei Wedding Str.', '13347');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Friedrichstr.', '27', 'Café Friedrichstr.', '10117');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Karl-Marx-Allee', '15', 'Imbiss Karl-Marx-Allee', '10243');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Müllerstraße', '10', 'Lieferservice Pizzeria', '10249');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Kurfürstendamm', '52', 'Café Central', '10707');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Schönhauser Allee', '13', 'Supermarkt Edeka', '10437');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Hauptstraße', '23', 'Bäckerei Schmidt', '12159');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Friedrichstraße', '123', 'Restaurant Zum Goldenen Lamm', '10117');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Unter den Linden', '12', 'Café Einstein', '10117');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Gneisenaustraße', '56', 'Imbiss Curry 36', '10961');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Mehringdamm', '89', 'Türkisches Restaurant', '10961');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Neue Promenade', '4', 'Sushi-Bar', '10178');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Kastanienallee', '78', 'Eiscafé', '10435');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Kantstraße', '12', 'Café am Neuen See', '10623');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Schlüterstraße', '34', 'Supermarkt Netto', '10629');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Uhlandstraße', '56', 'Gasthaus Zum Bären', '10719');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Kurfürstendamm', '12', 'Café Kranzler', '10719');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Prenzlauer Allee', '34', 'Supermarkt Aldi', '10405');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Schönhauser Allee', '123', 'MaxMustermann', '10119');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Kurfürstendamm', '456', 'SusiSorglos', '10789');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Hauptstraße', '78', 'KlausKäse', '12105');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Schloßstraße', '90', 'JuliaJogurt', '12157');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Sonnenallee', '12', 'HansHummus', '12059');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Mauerstraße', '34', 'PetraPesto', '10115');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Köpenicker Straße', '56', 'FrankFrikadelle', '10997');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Karl-Marx-Allee', '78', 'GabiGurke', '10178');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Eberswalder Straße', '90', 'KathrinKohlrabi', '10437');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Greifswalder Straße', '12', 'LarsLinsen', '10405');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Böckhstraße', '34', 'MonikaMöhren', '10965');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Fehrbelliner Straße', '56', 'NicoNudeln', '10719');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Herrfurthstraße', '78', 'OliverÖl', '12049');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Mainzer Straße', '90', 'PaulPaprika', '10247');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Oderstraße', '12', 'QuirinQuiche', '10365');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Müllerstraße', '5', 'Einkaufsgenie', '10178');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Kurfürstendamm', '23', 'FoodsharingFan', '10707');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Hauptstraße', '42', 'Lebensmittelretter', '12159');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Schönhauser Allee', '32', 'BerlinerGourmet', '10435');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Budapester Straße', '18', 'FoodwasteGegner', '10787');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Prenzlauer Allee', '99', 'NachhaltigerEinkauf', '10437');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Köpenicker Straße', '12', 'LebensmittelSparfuchs', '10997');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Friedrichstraße', '57', 'FoodsharingBerliner', '10117');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Invalidenstraße', '112', 'BerlinerGenießer', '10557');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Oranienburger Straße', '45', 'NachhaltigerLebensstil', '10117');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Unter den Linden', '6', 'BerlinerEsser', '10117');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Leipziger Straße', '78', 'BerlinerFoodsharing', '10117');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Alexanderstraße', '5', 'BerlinerSparfuchs', '10178');
INSERT INTO Spender (SpenderStrasse, SpenderHausnummer, SpenderName, SpenderPLZ) VALUES ('Weddinger Straße', '12', 'LebensmittelRetter', '13159');